### PR TITLE
Fix linker options

### PR DESCRIPTION
**Pull request by tbeu**
Closes https://github.com/tbeu/matio/issues/209

@seanm Please confirm if it works for you when using CMake &GreaterEqual; 3.17. Thanks.

### CODE REVIEW

**Comment by MaartenBent** [comment]
The `HAVE_LINK_EXPORTED_SYMBOLS_LIST` test always seems to fail, so now those flags are never added on macOS. I haven't been able to make it pass.
I suggest removing the test and changing the check to `elseif(APPLE AND HAVE_LINK_UNDEFINED_ERROR)`.

**Comment by tbeu** [comment]
> I suggest removing the test and changing the check to `elseif(APPLE AND HAVE_LINK_UNDEFINED_ERROR)`.

Done by https://github.com/tbeu/matio/pull/212/commits/400cfec4059d30bd918fb895bed9187e088a9b00.

**Comment by seanm** [comment]
Although I'm using macOS, my impression is this issue is related to AFL more than it is to macOS.  I would expect the same problem with AFL on linux too...

**Comment by seanm** [comment]
> Does the updated patch still work for you?

It does.

**Comment by tbeu** [comment]
> > Does the updated patch still work for you?
> 
> It does.

With invalidated CMake cache, I hope.

**Comment by MaartenBent** [comment]
Thanks for testing.

Maybe `--retain-symbols-file` works on Linux too when using clang and/or ldd. But I couldn't get it to work on Windows. Thats why I suggested to limit it to `APPLE` for now. Since these options were [originally](https://github.com/tbeu/matio/commit/c80718f4259654bdf40688ef3b21f92faa265e6c) added only for macOS because it didn't work with `--no-undefined`.

This should be unaffected by the CMake cache. The result variables of `check_linker_flag` are cached, but if/else is evaluated every time you rerun CMake. Though testing with a clean build directory is always good.

**Review by MaartenBent — APPROVED** [review]

**Pull request merged**
