### PR TITLE
Correct an overflow bug in Read5.

### PR DESCRIPTION
**Pull request by papadop**
This simple patch corrects issue #91.

### CODE REVIEW

**Comment by massich** [comment]
can we backport such fix to the current release and then add it to the conda package?

**Comment by tbeu** [comment]
Who is meant by "we"? But yes, I can cherry-pick it for the 1.5.12-branch.

**Comment by massich** [comment]
we -> anyone from the community with enough rights to do so. (aka tbeu)

**Comment by massich** [comment]
meanwhile you can merge this one https://github.com/conda-forge/libmatio-feedstock/pull/20 and then propagate the changes.

**Comment by tbeu** [comment]
Done, see https://github.com/tbeu/matio/tree/matio_1_5_12.

**Comment by massich** [comment]
but this one https://github.com/tbeu/matio/releases/tag/v1.5.12 still points to 6600c3d rather than 08873eb. While we update this, and the recipies. Can you merge https://github.com/conda-forge/libmatio-feedstock/pull/20

I'll submit a new PR reverting the patch and using the new release

**Comment by tbeu** [comment]
Well, I will not touch the tag for sure.

**Pull request merged**
