### PR TITLE
test against hdf5 shipped in brew

### PR DESCRIPTION
**Pull request by massich**

### CODE REVIEW

**Comment by tbeu** [comment]
@massich Do you plan to fix the travis config?

**Comment by massich** [comment]
It needed fixing in brew, and as far as I can tell it stall. I'm not sure if it's still broken.

**Comment by tbeu** [comment]
Can you rebase and force-push to trigger travis again?

**Comment by tbeu** [comment]
Still the same config problem that it does not built with hdf5 support.

**Comment by tbeu** [comment]
@massich How to proceed with this PR?

**Comment by tbeu** [comment]
Works when xcode 9.4 is used (instaed of 8.3).

**Pull request merged**
