### PR TITLE
Fix CMake shared linker options on macOS

### PR DESCRIPTION
**Pull request by MaartenBent**
See #172

The linker on macOS does not recognize the used linker options, so use different options that should have the same effect.
The `exported_symbols_list` option does not work with the names in `matio.sym`, it requires symbol names starting with `_`, so create a copy of `matio.sym` and modify it when necessary.
Symbol names starting with `_` also works with the GNU linker but not with the LLVM Linker on Linux, so don't modify the original file.

### CODE REVIEW

**Comment by MaartenBent** [comment]
Error seems not related to my CMake changes, but something related to conan/python (maybe it requires python3?).

**Comment by tbeu** [comment]
Thank you for the PR. Should we have a macos+CMake build at Travis CI, too?

**Comment by tbeu** [comment]
> Error seems not related to my CMake changes, but something related to conan/python (maybe it requires python3?).

Yes, I already noticed and thought it is related to the Conan cache. But Py3 is another useful hint.

**Comment by tbeu** [comment]
> Sure, let me add it.

Thank you. Very diligent work.

**Pull request merged**
