### PR TITLE
Fix unused return value of fread. 

### LINKED ISSUE #48: Remove GCC warnings on unused return value of fread
See https://travis-ci.org/tbeu/matio/jobs/169049417#L911-L914 for the GCC output with warnings on unused return value of fread.

### PR DESCRIPTION
**Pull request by vharsh**
Fixes #48

### CODE REVIEW

**Comment by tbeu** [comment]
Thanks for the PR. Can you fix the errors to make it compiling. Thanks again.

**Comment by vharsh** [comment]
I have fixed the initialization of variable in 4 functions, 
- Read5
- Mat_VarReadNumeric5
- ReadData5
- Mat_VarReadDataLinear5

I found a few other warnings which involved comparison of signed/unsigned data-members, use of fopen *instead of fopen_s* on AppVeyor
and I saw `ambiguous instructions require an explicit suffix` on Apple GCC.

**Comment by tbeu** [comment]
fopen_s is MSVc specific and will not work on GCC. Just ignore this warning.

**Comment by vharsh** [comment]
@tbeu I have `clang version 3.8.0` on Fedora24, could you please tell me how to reproduce this error on my machine? I tried copying and pasting some commands from the Travis-CI. Please give me some more hints to proceed further.

**Comment by tbeu** [comment]
Which error? From Travis CI OSX buildw? That is actually a current problem at Travis CI. I already contacted them and they confirmed.

**Comment by vharsh** [comment]
Oh, can you recommend me some great resources on C ? I am reading K&R, what more should I do?

**Comment by tbeu** [comment]
Merged by 39d07023f6d898c44e3f6c0a6920c7052057bd84. Thank you.

**Pull request closed without merging**
